### ISSUE TITLE
I would like to solve this problem. Is there a way??

### ISSUE THREAD

**Issue by youtubetakq** [RCVolus/lol-pick-ban-ui#133]
![캡처](https://user-images.githubusercontent.com/103791704/163652510-45142b79-45a8-4ce5-8998-b2bf934adfee.JPG)

I would like to solve this problem. Is there a way?? :(

https://nodejs.org/download/release/v16.7.0/node-v16.7.0-x64.msi 
Downloaded through here.

**Comment by sdomi4** [comment]
Hello :)

The npm commands need to be run in the respective backend and layout folders to work.
For the backend: run `npm install` in ...\lol-pick-ban-ui-master\backend
For the europe layout: run `npm install` in ...\lol-pick-ban-ui-master\layouts\layout-volu-europe

**Comment by youtubetakq** [comment]
답변해주셔서 감사합니다. 위 문제는 해결하였습니다.
설명을 보고 순서대로 설치 진행을 하였습니다.
하지만 이 문제가 발생합니다.
해결방법이 있나요?
![캡처 JPG](https://user-images.githubusercontent.com/103791704/163702900-8c780dad-03b5-445e-9908-8f4653f24d21.jpg)

**Comment by sdomi4** [comment]
The circled 0% is not an issue, this is just the asset download starting (champion images), you can see it completing 2 lines below.

The League Client needs to be open for the tool to work, this error message usually happens when the client closes.
You can test if everything works by opening League, starting backend and frontend, and then going into any champion select (practice tool for example).
