### ISSUE TITLE
the errors

### ISSUE THREAD

**Issue by Juzix1** [RCVolus/lol-pick-ban-ui#2]
when im starting the frontend using npm start Im getting some errors.
![image](https://user-images.githubusercontent.com/58827642/70750392-a14b7700-1d2e-11ea-9e47-641812f6fab1.png)

**Comment by LarsBaertschi** [comment]
Hey, you get exactly one error and it's telling you:
`Error: listen EADDRINUSE: address already in use :::8999`

This error tells you that the application tries to open a socket on port 8999, but fails to do so because port 8999 is already occupied. Please check that no other application is listening on that port - e.g. another instance of the application.

Btw in the message you write that you are starting the frontend, but this is actually the backend. The frontend is located in https://github.com/RCVolus/lol-pick-ban-ui/tree/master/layouts/layout-volu-europe

**Comment by Juzix1** [comment]
Oh ok, could i ask you how to build this application? to make it work.


pt., 13 gru 2019 o 08:45 Lars Bärtschi <notifications@github.com>
napisał(a):

**Comment by LarsBaertschi** [comment]
To build the frontend, you need to clone / check out the git repository (as you probably already did since you started the backend).

Then, head in the folder `layouts/layout-volu-europe` and spin up a command line.

Then execute the following two commands to first install all dependencies and start it afterwards:
```bash
npm install
npm start
```

The second command will open up a web page, but you will get an error. This is because no backend is provided. To launch it using a local backend (meaning you let the backend and the frontend run on the same machine) you need to open the url http://localhost:3000/?backend=ws://localhost:8999
