### ISSUE TITLE
Error on start server

### ISSUE THREAD

**Issue by douglaswender** [RCVolus/lol-pick-ban-ui#32]
I got this error when I tried to start the backend, I tried to adjust it but I couldn't find the reason, I use Windows 10 64 bits

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
     at LeagueDataProviderService.getCurrentData (lol-pick-ban-ui \ backend-build \ data \ league \ LeagueDataProviderService.js: 58: 97)

![image](https://user-images.githubusercontent.com/13887472/95153171-cfd28c80-075c-11eb-9e8c-1355c81823c7.png)

**Comment by LarsBaertschi** [comment]
Hey,

thank you for your report. Sorry, this error message is not really good and not guiding towards a potential solution. I'll try to have a look and create a follow up issue to fix the error message. The image you attached doesn't really show anything relevant, skipping those optional dependencies does not cause any issue.

Usually, this happens if the pick-ban-ui cannot connect to your league client. So make sure:
1. It's open.
2. If it's started as administrator, also make sure that you start the PowerShell as administrator. It cannot read from it if it was launched with higher permission else.

**Comment by LarsBaertschi** [comment]
Follow up issue: https://github.com/RCVolus/lol-pick-ban-ui/issues/33

Please let me know if the above answer should not fix your issue.

**Comment by douglaswender** [comment]
It is solved, it was problems with the same administrator permissions
