### ISSUE TITLE
Usage in normal games (outside of the spectator mode)

### ISSUE THREAD

**Issue by Gnaj** [RCVolus/lol-pick-ban-ui#55]
Hello, following up on the SoloQ-Flex topic, ive tried and i have to say it works quite well, Names, Summoner Spells, Intended Pick, Bans those are just spot on, however there are some things that do not work as good, for example Position/Role detection is not working at all in SoloQ-Flex queues, also, team sides.

Now to my question, i know of apps that can detect the role/position of given player during draft, is there a way that this could be added? or it would need to be a complete rewrite? same goes with team sides.

Thank you all, i know this is not the intended use for the program but still i'd be awesome. o/

**Comment by PieterVanZyl-Dev** [comment]
The position information isn't provided to my understanding, as there are
obvious problems around counter picks and such being abused if that data
was available.

I believe you can only see your team's position and the side of teams is
hinted at with who has first pick or not.
But the tool will always show your team on the left hand side I believe.

**Comment by LarsBaertschi** [comment]
Hey!

As Pieter mentioned, this data is just not provided, because it will be in the same order it's also displayed in champ select.

**About the issue**
To obtain the data, the pick-ban-ui backend service connects to your local League-Client via a local interface. There, it can fetch information about the current champ select. It will periodically pull this information, and the frontend will take care of visualising it. Information such as which team is red (right) / blue (left) and actual position ordering is not fully available.

For the own team, it could be possible to order roles by the selected position supplied (so always top comes first, regardless of where the player is in champ select) - although I'm not sure if it is in the data. Also this will come with the side effect, that top may not always actually pick first. So the order of things will then be rather random. But that's just how the League champ select in SR normal games works. For the enemy team, we don't have that information at all.

**Possible solutions**
While it is possible to try and do some tricks, like guessing what champion usually goes to what position and going from there, it may become possible to guess a bit more and maybe even in the enemy team where there is almost no information at all. But I see it out of scope for this project, but it could be a good starting version to go from. So you don't need to rewrite it all together, the software is built quite modular and is also extensible. So feel free to give it a try, I'm happy to see if anything becomes possible!

Best regards
Lars
