### ISSUE TITLE
in my folder are missing some champion like, zoe, yone, veigo. How can i update e splash arts from chamions ?

### ISSUE THREAD

**Issue by Rafaelmtds** [RCVolus/lol-pick-ban-ui#88]
![,](https://user-images.githubusercontent.com/37699874/118410434-ccde3980-b665-11eb-87af-01b638b8651b.png)

**Comment by LarsBaertschi** [comment]
Hello! Unfortunately currently we do not have any checks for partial missing champions. So in order to fix the issue, you have to remove the local cache of the affected patch: delete the folder "cache/{patch}" (in your case: cache/11.10.1) including all content in that folder. After you restart the service, it will notice that the local cache is missing and will redownload it. If the issue of missing champions persists after this, let me know!

**Comment by SixiNeri** [comment]
Its work, thank you
